/* Generated by JavaFromJSON */
/*http://javafromjson.dashingrocket.com*/

package com.aiss.gamingguru.shared.amazon;

import java.io.Serializable;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;


@JsonIgnoreProperties(ignoreUnknown=true)
public class Amazon implements Serializable {
	/**
	 * 
	 */
	private static final long serialVersionUID = -7233163385609426286L;
	private ItemSearchResponse itemsearchresponse;

 	public void setItemsearchresponse(ItemSearchResponse itemsearchresponse) {
		this.itemsearchresponse = itemsearchresponse;
	}

	public ItemSearchResponse getItemsearchresponse() {
		return itemsearchresponse;
	}

}