/* Generated by JavaFromJSON */
/*http://javafromjson.dashingrocket.com*/

package com.aiss.gamingguru.shared.amazon;

import java.io.Serializable;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;


@JsonIgnoreProperties(ignoreUnknown=true)
public class Arguments implements Serializable{
	/**
	 * 
	 */
	private static final long serialVersionUID = -8808619295465046307L;
	/**
	 * 
	 */
	private ArgumentElement[] argument;

 	public void setArgument(ArgumentElement[] argument) {
		this.argument = argument;
	}

	public ArgumentElement[] getArgument() {
		return argument;
	}

}