/* Generated by JavaFromJSON */
/*http://javafromjson.dashingrocket.com*/

package com.aiss.gamingguru.shared.amazon;

import java.io.Serializable;

import org.codehaus.jackson.annotate.JsonIgnoreProperties;

@JsonIgnoreProperties(ignoreUnknown=true)
public class ArgumentElement implements Serializable{
	/**
	 * 
	 */
	private static final long serialVersionUID = -3211996722857903229L;
	/**
	 * 
	 */
	private java.lang.String _value;

 	public void set_value(java.lang.String _value) {
		this._value = _value;
	}

	public java.lang.String get_value() {
		return _value;
	}

	private java.lang.String _name;

 	public void set_name(java.lang.String _name) {
		this._name = _name;
	}

	public java.lang.String get_name() {
		return _name;
	}

}