/* Generated by JavaFromJSON */
/*http://javafromjson.dashingrocket.com*/

package com.aiss.gamingguru.shared.amazon;

import java.io.Serializable;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;

@JsonIgnoreProperties(ignoreUnknown=true)
public class EANList implements Serializable{
	/**
	 * 
	 */
	private static final long serialVersionUID = -5350209866383828873L;
	/**
	 * 
	 */
	private java.lang.String eanlistelement;

 	public void setEanlistelement(java.lang.String eanlistelement) {
		this.eanlistelement = eanlistelement;
	}

	public java.lang.String getEanlistelement() {
		return eanlistelement;
	}

}