/* Generated by JavaFromJSON */
/*http://javafromjson.dashingrocket.com*/

package com.aiss.gamingguru.shared.amazon;

import java.io.Serializable;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;

@JsonIgnoreProperties(ignoreUnknown=true)
public class ImageSets implements Serializable{
	/**
	 * 
	 */
	private static final long serialVersionUID = -8816264448508460718L;
	/**
	 * 
	 */
	private ImageSetElement[] imageset;

 	public void setImageset(ImageSetElement[] imageset) {
		this.imageset = imageset;
	}

	public ImageSetElement[] getImageset() {
		return imageset;
	}

}