/* Generated by JavaFromJSON */
/*http://javafromjson.dashingrocket.com*/

package com.aiss.gamingguru.shared.amazon;

import java.io.Serializable;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;

@JsonIgnoreProperties(ignoreUnknown=true)
public class Items implements Serializable{
	/**
	 * 
	 */
	private static final long serialVersionUID = 6058066394064416011L;
	/**
	 * 
	 */
	private Request request;

 	public void setRequest(Request request) {
		this.request = request;
	}

	public Request getRequest() {
		return request;
	}

	private java.lang.String moresearchresultsurl;

 	public void setMoresearchresultsurl(java.lang.String moresearchresultsurl) {
		this.moresearchresultsurl = moresearchresultsurl;
	}

	public java.lang.String getMoresearchresultsurl() {
		return moresearchresultsurl;
	}

	private java.lang.String totalresults;

 	public void setTotalresults(java.lang.String totalresults) {
		this.totalresults = totalresults;
	}

	public java.lang.String getTotalresults() {
		return totalresults;
	}

	private java.lang.String totalpages;

 	public void setTotalpages(java.lang.String totalpages) {
		this.totalpages = totalpages;
	}

	public java.lang.String getTotalpages() {
		return totalpages;
	}

	private ItemElement[] item;

 	public void setItem(ItemElement[] item) {
		this.item = item;
	}

	public ItemElement[] getItem() {
		return item;
	}

}