/* Generated by JavaFromJSON */
/*http://javafromjson.dashingrocket.com*/

package com.aiss.gamingguru.shared.amazon;

import java.io.Serializable;

import org.codehaus.jackson.annotate.JsonIgnoreProperties;

@JsonIgnoreProperties(ignoreUnknown=true)
public class ItemSearchRequest implements Serializable{
	/**
	 * 
	 */
	private static final long serialVersionUID = 4007899513013277008L;
	/**
	 * 
	 */
	private java.lang.String searchindex;

 	public void setSearchindex(java.lang.String searchindex) {
		this.searchindex = searchindex;
	}

	public java.lang.String getSearchindex() {
		return searchindex;
	}

	private java.lang.String keywords;

 	public void setKeywords(java.lang.String keywords) {
		this.keywords = keywords;
	}

	public java.lang.String getKeywords() {
		return keywords;
	}

	private java.lang.String sort;

 	public void setSort(java.lang.String sort) {
		this.sort = sort;
	}

	public java.lang.String getSort() {
		return sort;
	}

	private java.lang.String[] responsegroup;

 	public void setResponsegroup(java.lang.String[] responsegroup) {
		this.responsegroup = responsegroup;
	}

	public java.lang.String[] getResponsegroup() {
		return responsegroup;
	}

}