/* Generated by JavaFromJSON */
/*http://javafromjson.dashingrocket.com*/

package com.aiss.gamingguru.shared.amazon;

import java.io.Serializable;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;

@JsonIgnoreProperties(ignoreUnknown=true)
public class ItemSearchResponse implements Serializable{
	/**
	 * 
	 */
	private static final long serialVersionUID = -7078936290866799096L;
	/**
	 * 
	 */
	private OperationRequest operationrequest;

 	public void setOperationrequest(OperationRequest operationrequest) {
		this.operationrequest = operationrequest;
	}

	public OperationRequest getOperationrequest() {
		return operationrequest;
	}

	private Items items;

 	public void setItems(Items items) {
		this.items = items;
	}

	public Items getItems() {
		return items;
	}

	private java.lang.String _xmlns;

 	public void set_xmlns(java.lang.String _xmlns) {
		this._xmlns = _xmlns;
	}

	public java.lang.String get_xmlns() {
		return _xmlns;
	}

}