/* Generated by JavaFromJSON */
/*http://javafromjson.dashingrocket.com*/

package com.aiss.gamingguru.shared.amazon;

import java.io.Serializable;

import org.codehaus.jackson.annotate.JsonIgnoreProperties;

@JsonIgnoreProperties(ignoreUnknown=true)
public class ItemAttributes implements Serializable {
	/**
	 * 
	 */
	private static final long serialVersionUID = 5485591964631637298L;
	/**
	 * 
	 */
	private ManufacturerMinimumAge manufacturerminimumage;

 	public void setManufacturerminimumage(ManufacturerMinimumAge manufacturerminimumage) {
		this.manufacturerminimumage = manufacturerminimumage;
	}

	public ManufacturerMinimumAge getManufacturerminimumage() {
		return manufacturerminimumage;
	}

	private PackageDimensions packagedimensions;

 	public void setPackagedimensions(PackageDimensions packagedimensions) {
		this.packagedimensions = packagedimensions;
	}

	public PackageDimensions getPackagedimensions() {
		return packagedimensions;
	}

	private ListPrice listprice;

 	public void setListprice(ListPrice listprice) {
		this.listprice = listprice;
	}

	public ListPrice getListprice() {
		return listprice;
	}

	private EANList eanlist;

 	public void setEanlist(EANList eanlist) {
		this.eanlist = eanlist;
	}

	public EANList getEanlist() {
		return eanlist;
	}

	private ItemDimensions itemdimensions;

 	public void setItemdimensions(ItemDimensions itemdimensions) {
		this.itemdimensions = itemdimensions;
	}

	public ItemDimensions getItemdimensions() {
		return itemdimensions;
	}

	private Languages languages;

 	public void setLanguages(Languages languages) {
		this.languages = languages;
	}

	public Languages getLanguages() {
		return languages;
	}

	private java.lang.String title;

 	public void setTitle(java.lang.String title) {
		this.title = title;
	}

	public java.lang.String getTitle() {
		return title;
	}

	private java.lang.String producttypename;

 	public void setProducttypename(java.lang.String producttypename) {
		this.producttypename = producttypename;
	}

	public java.lang.String getProducttypename() {
		return producttypename;
	}

	private java.lang.String brand;

 	public void setBrand(java.lang.String brand) {
		this.brand = brand;
	}

	public java.lang.String getBrand() {
		return brand;
	}

	private java.lang.String studio;

 	public void setStudio(java.lang.String studio) {
		this.studio = studio;
	}

	public java.lang.String getStudio() {
		return studio;
	}

	private java.lang.String hardwareplatform;

 	public void setHardwareplatform(java.lang.String hardwareplatform) {
		this.hardwareplatform = hardwareplatform;
	}

	public java.lang.String getHardwareplatform() {
		return hardwareplatform;
	}

	private java.lang.String ean;

 	public void setEan(java.lang.String ean) {
		this.ean = ean;
	}

	public java.lang.String getEan() {
		return ean;
	}

	private java.lang.String label;

 	public void setLabel(java.lang.String label) {
		this.label = label;
	}

	public java.lang.String getLabel() {
		return label;
	}

	private java.lang.String operatingsystem;

 	public void setOperatingsystem(java.lang.String operatingsystem) {
		this.operatingsystem = operatingsystem;
	}

	public java.lang.String getOperatingsystem() {
		return operatingsystem;
	}

	private java.lang.String binding;

 	public void setBinding(java.lang.String binding) {
		this.binding = binding;
	}

	public java.lang.String getBinding() {
		return binding;
	}

	private java.lang.String platform;

 	public void setPlatform(java.lang.String platform) {
		this.platform = platform;
	}

	public java.lang.String getPlatform() {
		return platform;
	}

	private java.lang.String releasedate;

 	public void setReleasedate(java.lang.String releasedate) {
		this.releasedate = releasedate;
	}

	public java.lang.String getReleasedate() {
		return releasedate;
	}

	private java.lang.String publisher;

 	public void setPublisher(java.lang.String publisher) {
		this.publisher = publisher;
	}

	public java.lang.String getPublisher() {
		return publisher;
	}

	private java.lang.String manufacturer;

 	public void setManufacturer(java.lang.String manufacturer) {
		this.manufacturer = manufacturer;
	}

	public java.lang.String getManufacturer() {
		return manufacturer;
	}

	private java.lang.String productgroup;

 	public void setProductgroup(java.lang.String productgroup) {
		this.productgroup = productgroup;
	}

	public java.lang.String getProductgroup() {
		return productgroup;
	}

}