/* Generated by JavaFromJSON */
/*http://javafromjson.dashingrocket.com*/

package com.aiss.gamingguru.shared.amazon;

import java.io.Serializable;

import org.codehaus.jackson.annotate.JsonIgnoreProperties;

@JsonIgnoreProperties(ignoreUnknown=true)
public class Languages implements Serializable {
	/**
	 * 
	 */
	private static final long serialVersionUID = 7485763954105215315L;
	/**
	 * 
	 */
	private LanguageElement[] language;

 	public void setLanguage(LanguageElement[] language) {
		this.language = language;
	}

	public LanguageElement[] getLanguage() {
		return language;
	}

}