/* Generated by JavaFromJSON */
/*http://javafromjson.dashingrocket.com*/

package com.aiss.gamingguru.shared.amazon;

import java.io.Serializable;

import org.codehaus.jackson.annotate.JsonIgnoreProperties;

@JsonIgnoreProperties(ignoreUnknown=true)
public class Length implements Serializable{
	/**
	 * 
	 */
	private static final long serialVersionUID = -66574227072019877L;
	/**
	 * 
	 */
	private java.lang.String __text;

 	public void set__text(java.lang.String __text) {
		this.__text = __text;
	}

	public java.lang.String get__text() {
		return __text;
	}

	private java.lang.String _units;

 	public void set_units(java.lang.String _units) {
		this._units = _units;
	}

	public java.lang.String get_units() {
		return _units;
	}

}