/* Generated by JavaFromJSON */
/*http://javafromjson.dashingrocket.com*/

package com.aiss.gamingguru.shared.amazon;

import java.io.Serializable;

import org.codehaus.jackson.annotate.JsonIgnoreProperties;

@JsonIgnoreProperties(ignoreUnknown=true)
public class LowestNewPrice implements Serializable{
	/**
	 * 
	 */
	private static final long serialVersionUID = -2561536060778455179L;
	/**
	 * 
	 */
	private java.lang.String currencycode;

 	public void setCurrencycode(java.lang.String currencycode) {
		this.currencycode = currencycode;
	}

	public java.lang.String getCurrencycode() {
		return currencycode;
	}

	private java.lang.String amount;

 	public void setAmount(java.lang.String amount) {
		this.amount = amount;
	}

	public java.lang.String getAmount() {
		return amount;
	}

	private java.lang.String formattedprice;

 	public void setFormattedprice(java.lang.String formattedprice) {
		this.formattedprice = formattedprice;
	}

	public java.lang.String getFormattedprice() {
		return formattedprice;
	}

}