/* Generated by JavaFromJSON */
/*http://javafromjson.dashingrocket.com*/

package com.aiss.gamingguru.shared.amazon;

import java.io.Serializable;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;

@JsonIgnoreProperties(ignoreUnknown=true)
public class MediumImage implements Serializable{
	/**
	 * 
	 */
	private static final long serialVersionUID = -1830289018620520961L;
	/**
	 * 
	 */
	private Width width;

 	public void setWidth(Width width) {
		this.width = width;
	}

	public Width getWidth() {
		return width;
	}

	private Height height;

 	public void setHeight(Height height) {
		this.height = height;
	}

	public Height getHeight() {
		return height;
	}

	private java.lang.String url;

 	public void setUrl(java.lang.String url) {
		this.url = url;
	}

	public java.lang.String getUrl() {
		return url;
	}

}