/* Generated by JavaFromJSON */
/*http://javafromjson.dashingrocket.com*/

package com.aiss.gamingguru.shared.amazon;

import java.io.Serializable;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;

@JsonIgnoreProperties(ignoreUnknown=true)
public class Offers implements Serializable{
	/**
	 * 
	 */
	private static final long serialVersionUID = 8582247566298329540L;
	/**
	 * 
	 */
	private java.lang.String totalofferpages;

 	public void setTotalofferpages(java.lang.String totalofferpages) {
		this.totalofferpages = totalofferpages;
	}

	public java.lang.String getTotalofferpages() {
		return totalofferpages;
	}

	private java.lang.String moreoffersurl;

 	public void setMoreoffersurl(java.lang.String moreoffersurl) {
		this.moreoffersurl = moreoffersurl;
	}

	public java.lang.String getMoreoffersurl() {
		return moreoffersurl;
	}

	private java.lang.String totaloffers;

 	public void setTotaloffers(java.lang.String totaloffers) {
		this.totaloffers = totaloffers;
	}

	public java.lang.String getTotaloffers() {
		return totaloffers;
	}

}