/* Generated by JavaFromJSON */
/*http://javafromjson.dashingrocket.com*/

package com.aiss.gamingguru.shared.amazon;

import java.io.Serializable;

import org.codehaus.jackson.annotate.JsonIgnoreProperties;

@JsonIgnoreProperties(ignoreUnknown=true)
public class OperationRequest implements Serializable{
	/**
	 * 
	 */
	private static final long serialVersionUID = 7530277544523264242L;
	/**
	 * 
	 */
	private Arguments arguments;

 	public void setArguments(Arguments arguments) {
		this.arguments = arguments;
	}

	public Arguments getArguments() {
		return arguments;
	}

	private java.lang.String requestprocessingtime;

 	public void setRequestprocessingtime(java.lang.String requestprocessingtime) {
		this.requestprocessingtime = requestprocessingtime;
	}

	public java.lang.String getRequestprocessingtime() {
		return requestprocessingtime;
	}

	private java.lang.String requestid;

 	public void setRequestid(java.lang.String requestid) {
		this.requestid = requestid;
	}

	public java.lang.String getRequestid() {
		return requestid;
	}

}