/* Generated by JavaFromJSON */
/*http://javafromjson.dashingrocket.com*/

package com.aiss.gamingguru.shared.amazon;

import java.io.Serializable;

import org.codehaus.jackson.annotate.JsonIgnoreProperties;

@JsonIgnoreProperties(ignoreUnknown=true)
public class PackageDimensions implements Serializable{
	/**
	 * 
	 */
	private static final long serialVersionUID = -8298751786796074432L;
	/**
	 * 
	 */
	private Width width;

 	public void setWidth(Width width) {
		this.width = width;
	}

	public Width getWidth() {
		return width;
	}

	private Height height;

 	public void setHeight(Height height) {
		this.height = height;
	}

	public Height getHeight() {
		return height;
	}

	private Length length;

 	public void setLength(Length length) {
		this.length = length;
	}

	public Length getLength() {
		return length;
	}

	private Weight weight;

 	public void setWeight(Weight weight) {
		this.weight = weight;
	}

	public Weight getWeight() {
		return weight;
	}

}