/* Generated by JavaFromJSON */
/*http://javafromjson.dashingrocket.com*/

package com.aiss.gamingguru.shared.amazon;

import java.io.Serializable;

import org.codehaus.jackson.annotate.JsonIgnoreProperties;

@JsonIgnoreProperties(ignoreUnknown=true)
public class Request implements Serializable{
	/**
	 * 
	 */
	private static final long serialVersionUID = -8381254143074348892L;
	private ItemSearchRequest itemsearchrequest;

 	public void setItemsearchrequest(ItemSearchRequest itemsearchrequest) {
		this.itemsearchrequest = itemsearchrequest;
	}

	public ItemSearchRequest getItemsearchrequest() {
		return itemsearchrequest;
	}

	private java.lang.String isvalid;

 	public void setIsvalid(java.lang.String isvalid) {
		this.isvalid = isvalid;
	}

	public java.lang.String getIsvalid() {
		return isvalid;
	}

}